### ISSUE TITLE
Roadmap 컴포넌트 관련 이슈

### ISSUE THREAD

**Issue by raejoonee** [YAPP-19th/Web-Team-1-Frontend#38]
* [x] 로드맵 최하단부 렌더링이 일부 어색한 현상 수정
* [x] 로드맵 컨텐츠가 좌우 번갈아가면서 나타나도록 수정
* [x] 퀘스트가 존재하는 경우와 아닌 경우 다르게 나타나도록 수정
