### ISSUE TITLE
2차 QA 현황 🔥

### ISSUE THREAD

**Issue by raejoonee** [YAPP-19th/Web-Team-1-Frontend#55]
### 상세보기 페이지
* [x] 한 줄 후기 작성 (#50 에서 이어받음)
* [x] 퀘스트 포기 (#50 에서 이어받음)
* [x] 서브퀘스트 달성 안하고 퀘스트 완료눌렀을 때  완료 안되었지만 '퀘스트 완료 토스트 메뉴' 뜸

### 로드맵 생성 페이지 & 프로필 퀘스트 페이지
* [x] 퀘스트 상세보기 모달 (#50 에서 이어받음)

### 새로고침
- [x] 퀘스트 달성률 새로고침해야 적용되는 문제
- [x] 퀘스트 한 줄 후기 새로고침해야 적용되는 문제

## @kyoung-jnn 
- [x] 퀘스트 등록 난이도 표시 문제
- [x] 썸네일 디폴트
- [x] 회원가입 글씨 크기
- [ ] 퀘스트 페이지에서 접근하면 마우스 스크롤 최상위로 올라가기
- [x] 헤더 닉네임 표시
- [x] 커뮤니티 플로팅 버튼

### 프로필 페이지
- [x] 퀘스트 진행 중 포기 (#50 에서 이어받음)
- [x] 썸네일 알파 50%
- [x] ~~프로필 자기소개 업데이트 / 새로고침~~ **(😶안 고쳤는데 잘 됨..)**
- [x] 직군 하나밖에 없을 때 UsersMe 수정 시 직군 Dropdown 메뉴 안 생기도록 수정
### 항해 업적 페이지
- [x] 업적 순서 뒤집기 (1급 ~ 5급 -> 5급 ~ 1급)
### 공통
* [x] difficulty: https://github.com/YAPP-19th/Web-Team-1-Frontend/pull/53#discussion_r783907925
* [x] iconLevel: https://github.com/YAPP-19th/Web-Team-1-Frontend/pull/53#discussion_r783911025

**Comment by ayoung0073** [comment]
## 사소한 QA 적어봐요 희희.. 🙏
###  퀘스트 리스트 페이지
- [x] 세로 중앙 정렬이 되지 않은 부분들이 보여요! 
- [x] 그리고 `0 참여 중`에 `명` 추가 부탁드려요~!
- [x] 퀘스트 리스트 페이지에서 경험치가 0xp가 나오던데 확인 부탁드려요!
- [x] 밑에처럼 일자 맞춰주시면 감사하겠슴니다 🙇🏻‍♀️
![image](https://user-images.githubusercontent.com/69340410/149533076-59416184-050d-4134-a89e-308b06385c5c.png)
- [x] 아이콘눌렀을 때 글자색이 피그마랑 다른 것 같아요! 
![image](https://user-images.githubusercontent.com/69340410/149535648-641740d5-2e1a-463d-8fa2-78fe1f781d47.png)
- [x] 퀘스트 썸네일 보이게 해주세요!

### 퀘스트 생성 페이지
- [x] 퀘스트 생성이랑 설명 사이 공백이 좀 더 있어야할 것 같아요! 피그마 확인해주세용~
![image](https://user-images.githubusercontent.com/69340410/149537617-72d2885e-4c4d-428b-996d-14f67d49424e.png)
- [x] 퀘스트 제목 글자 수 제한 늘려주세요!
- [x] 난이도 설정을 하면 2라고 나오는데 "중급"으로 나와야 할 것 같아요. 입문을 선택하면 "난이도 설정"이라고 나와요!
- [x] 영어, 한글 통일되면 좋겠어요
![image](https://user-images.githubusercontent.com/69340410/149531483-67fbdda4-82b3-4508-8488-8133865791fa.png)

### 퀘스트 상세정보 페이지
- [x] ~~퀘스트 "수락" 워딩을 "참여"로 바꿔주세요!!~~ 래준님 의견에 납득되었습니다 짱!


 ❤️  프 론 트 여 러 분 화 이 팅 ❤️

**Comment by raejoonee** [comment]
@ayoung0073 😢 😭 😢 😭 😢 😭 😢 😭 😢 😭 😢 😭

**Comment by sohyeon-design** [comment]
- [x] 직군 선택이 Front밖에없서용ㅠㅠ

![image](https://user-images.githubusercontent.com/89681679/149537370-0cd10d68-3071-41b2-ad16-36a23e8dfc50.png)

- [x] 체크박스 클릭해도 프로그래스바가 0%에서 안올라염.. 윈도우가 윈도우했나..

![image](https://user-images.githubusercontent.com/89681679/149537686-eb6b98ae-a208-4748-922a-45fe746ca79f.png)

- [x] 오예스 가로본능 ㄷㄷ
![image](https://user-images.githubusercontent.com/89681679/149538169-0540bea8-5f58-4faf-bf8f-d6521f156702.png)

- [ ] 생성된 퀘스트만 넣었는데 링크가 안넘어가여
![image](https://user-images.githubusercontent.com/89681679/149538295-7baa7f04-35de-470b-a9a1-6a071dac97db.png)


❤️ 청 어 람 ❤️
